local _, Namespace = ...

---@class Private
local Private = Namespace
local L = Private.L

-- Credit to Treebonker and OmniCD for this entire data structure
Private.spellDB = {
	classes = {
		["WARRIOR"] = {
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Taunt",
				["spellID"] = 355,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Shield Block",
				["spellID"] = 2565,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Pummel",
				["spellID"] = 6552,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Charge",
				["spellID"] = 100,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Sweeping Strikes",
				["spellID"] = 260708,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Die by the Sword",
				["spellID"] = 118038,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Skullsplitter",
				["spellID"] = 260643,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Warbreaker",
				["spellID"] = 262161,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Colossus Smash",
				["spellID"] = 167105,
				["talent"] = 262161,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Last Stand",
				["spellID"] = 12975,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Demoralizing Shout",
				["spellID"] = 1160,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Disrupting Shout",
				["spellID"] = 386071,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Challenging Shout",
				["spellID"] = 1161,
				["talent"] = 386071,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Shield Wall",
				["spellID"] = 871,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Shield Charge",
				["spellID"] = 385952,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Impending Victory",
				["spellID"] = 202168,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Intervene",
				["spellID"] = 3411,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Group Utility"],
				["name"] = "Rallying Cry",
				["spellID"] = 97462,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Storm Bolt",
				["spellID"] = 107570,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Heroic Leap",
				["spellID"] = 6544,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Piercing Howl",
				["spellID"] = 12323,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Berserker Shout",
				["spellID"] = 384100,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Shattering Throw",
				["spellID"] = 64382,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Wrecking Throw",
				["spellID"] = 384110,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Bitter Immunity",
				["spellID"] = 383762,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["name"] = "Thunderous Roar",
				["spellID"] = 384318,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["name"] = "Avatar",
				["spellID"] = 107574,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Berserker Rage",
				["spellID"] = 18499,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Shockwave",
				["spellID"] = 46968,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["name"] = "Champion's Spear",
				["spellID"] = 376079,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["name"] = "Intimidating Shout",
				["spellID"] = 5246,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["name"] = "Spell Reflection",
				["spellID"] = 23920,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Ravager",
				["spellID"] = 228920,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Enraged Regeneration",
				["spellID"] = 184364,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Recklessness",
				["spellID"] = 1719,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Odyn's Fury",
				["spellID"] = 385059,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Bladestorm",
				["spellID"] = 227847,
			},
			{
				["class"] = "WARRIOR",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Demolish",
				["spellID"] = 436358,
			},
		},
		["ROGUE"] = {
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Between the Eyes",
				["spellID"] = 315341,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Group Utility"],
				["name"] = "Shroud of Concealment",
				["spellID"] = 114018,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Kidney Shot",
				["spellID"] = 408,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Kick",
				["spellID"] = 1766,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Distract",
				["spellID"] = 1725,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Crimson Vial",
				["spellID"] = 185311,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Vanish",
				["spellID"] = 1856,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["spec"] = 261,
				["name"] = "Symbols of Death",
				["spellID"] = 212283,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Sprint",
				["spellID"] = 2983,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Personal Defensive"],
				["name"] = "Feint",
				["spellID"] = 1966,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Blade Rush",
				["spellID"] = 271877,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Keep It Rolling",
				["spellID"] = 381989,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Roll the Bones",
				["spellID"] = 315508,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Adrenaline Rush",
				["spellID"] = 13750,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Killing Spree",
				["spellID"] = 51690,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Blade Flurry",
				["spellID"] = 13877,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Ghostly Strike",
				["spellID"] = 196937,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Grappling Hook",
				["spellID"] = 195457,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Blind",
				["spellID"] = 2094,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Tricks of the Trade",
				["spellID"] = 57934,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Shadowstep",
				["spellID"] = 36554,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Personal Defensive"],
				["name"] = "Cloak of Shadows",
				["spellID"] = 31224,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Secret Technique",
				["spellID"] = 280719,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Shuriken Tornado",
				["spellID"] = 277925,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Flagellation",
				["spellID"] = 384631,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Shadow Blades",
				["spellID"] = 121471,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Shiv",
				["spellID"] = 5938,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Gouge",
				["spellID"] = 1776,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Cold Blood",
				["spellID"] = 382245,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Other"],
				["name"] = "Thistle Tea",
				["spellID"] = 381623,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Personal Defensive"],
				["name"] = "Evasion",
				["spellID"] = 5277,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Deathmark",
				["spellID"] = 360194,
			},
			{
				["class"] = "ROGUE",
				["type"] = L["Core"],
				["name"] = "Kingsbane",
				["spellID"] = 385627,
			},
		},
		["DEMONHUNTER"] = {
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Blur",
				["spellID"] = 198589,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Infernal Strike",
				["spellID"] = 189110,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Fel Rush",
				["spellID"] = 195072,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Demon Spikes",
				["spellID"] = 203720,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Torment",
				["spellID"] = 185245,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Spectral Sight",
				["spellID"] = 188501,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Core"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Metamorphosis",
				["spellID"] = 187827,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Metamorphosis",
				["spellID"] = 191427,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Immolation Aura",
				["spellID"] = 258920,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Disrupt",
				["spellID"] = 183752,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Netherwalk",
				["spellID"] = 196555,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Core"],
				["name"] = "The Hunt",
				["spellID"] = 370965,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Felblade",
				["spellID"] = 232893,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Vengeful Retreat",
				["spellID"] = 198793,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Sigil of Flame",
				["spellID"] = 204596,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Sigil of Misery",
				["spellID"] = 207684,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Fiery Brand",
				["spellID"] = 204021,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Sigil of Chains",
				["spellID"] = 202138,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Soul Barrier",
				["spellID"] = 263648,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Bulk Extraction",
				["spellID"] = 320341,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Sigil of Spite",
				["spellID"] = 390163,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Soul Carver",
				["spellID"] = 207407,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Sigil of Silence",
				["spellID"] = 202137,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Core"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Fel Devastation",
				["spellID"] = 212084,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Chaos Nova",
				["spellID"] = 179057,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Group Utility"],
				["name"] = "Darkness",
				["spellID"] = 196718,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Consume Magic",
				["spellID"] = 278326,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["name"] = "Imprison",
				["spellID"] = 217832,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Fel Eruption",
				["spellID"] = 211881,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Eye Beam",
				["spellID"] = 198013,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Fel Barrage",
				["spellID"] = 258925,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Glaive Tempest",
				["spellID"] = 342817,
			},
			{
				["class"] = "DEMONHUNTER",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Essence Break",
				["spellID"] = 258860,
			},
		},
		["MONK"] = {
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Detox",
				["spellID"] = 115450,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Mana Tea",
				["spellID"] = 115869,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Touch of Death",
				["spellID"] = 322109,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Provoke",
				["spellID"] = 115546,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Leg Sweep",
				["spellID"] = 119381,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Transcendence: Transfer",
				["spellID"] = 119996,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Roll",
				["spellID"] = 109132,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true, ["role:damager"] = true },
				["name"] = "Jadefire Stomp",
				["spellID"] = 388193,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Song of Chi-Ji",
				["spellID"] = 198898,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Refreshing Jade Wind",
				["spellID"] = 196725,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Restoral",
				["spellID"] = 388615,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Revival",
				["spellID"] = 115310,
			},
			{
				["class"] = "MONK",
				["type"] = L["External Defensive"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Life Cocoon",
				["spellID"] = 116849,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Invoke Yu'lon, the Jade Serpent",
				["spellID"] = 322118,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Invoke Chi-Ji, the Red Crane",
				["spellID"] = 325197,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Thunder Focus Tea",
				["spellID"] = 116680,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Detox",
				["spellID"] = 218164,
			},
			{
				["class"] = "MONK",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Touch of Karma",
				["spellID"] = 122470,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Fists of Fury",
				["spellID"] = 113656,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Storm, Earth, and Fire",
				["spellID"] = 137639,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Flying Serpent Kick",
				["spellID"] = 101545,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Clash",
				["spellID"] = 324312,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Black Ox Brew",
				["spellID"] = 115399,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Summon Black Ox Statue",
				["spellID"] = 115315,
			},
			{
				["class"] = "MONK",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Celestial Brew",
				["spellID"] = 322507,
			},
			{
				["class"] = "MONK",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Celestial Infusion",
				["spellID"] = 1241059,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Invoke Xuen, the White Tiger",
				["spellID"] = 123904,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Whirling Dragon Punch",
				["spellID"] = 152175,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Strike of the Windlord",
				["spellID"] = 392983,
			},
			{
				["class"] = "MONK",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Fortifying Brew",
				["spellID"] = 115203,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Chi Torpedo",
				["spellID"] = 115008,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Spear Hand Strike",
				["spellID"] = 116705,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Paralysis",
				["spellID"] = 115078,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Tiger's Lust",
				["spellID"] = 116841,
			},
			{
				["class"] = "MONK",
				["type"] = L["Personal Defensive"],
				["name"] = "Diffuse Magic",
				["spellID"] = 122783,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Ring of Peace",
				["spellID"] = 116844,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Summon White Tiger Statue",
				["spellID"] = 388686,
			},
			{
				["class"] = "MONK",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Dampen Harm",
				["spellID"] = 122278,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["name"] = "Chi Burst",
				["spellID"] = 123986,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Weapons of Order",
				["spellID"] = 387184,
			},
			{
				["class"] = "MONK",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Exploding Keg",
				["spellID"] = 325153,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Invoke Niuzao, the Black Ox",
				["spellID"] = 132578,
			},
			{
				["class"] = "MONK",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Purifying Brew",
				["spellID"] = 119582,
			},
			{
				["class"] = "MONK",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true, ["role:healer"] = true },
				["name"] = "Celestial Conduit",
				["spellID"] = 443028,
			},
		},
		["DEATHKNIGHT"] = {
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["name"] = "Lichborne",
				["spellID"] = 49039,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["name"] = "Death's Advance",
				["spellID"] = 48265,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Group Utility"],
				["name"] = "Death Grip",
				["spellID"] = 49576,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["name"] = "Dark Command",
				["spellID"] = 56222,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Raise Abomination",
				["spellID"] = 455395,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Remorseless Winter",
				["spellID"] = 196770,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["name"] = "Blinding Sleet",
				["spellID"] = 207167,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Empower Rune Weapon",
				["spellID"] = 47568,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["name"] = "Asphyxiate",
				["spellID"] = 221562,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Group Utility"],
				["name"] = "Anti-Magic Zone",
				["spellID"] = 51052,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["name"] = "Anti-Magic Shell",
				["spellID"] = 48707,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["name"] = "Raise Dead",
				["spellID"] = 46585,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["name"] = "Sacrificial Pact",
				["spellID"] = 327574,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["name"] = "Death Pact",
				["spellID"] = 48743,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["name"] = "Wraith Walk",
				["spellID"] = 212552,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["name"] = "Mind Freeze",
				["spellID"] = 47528,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["name"] = "Icebound Fortitude",
				["spellID"] = 48792,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Breath of Sindragosa",
				["spellID"] = 152279,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Frostwyrm's Fury",
				["spellID"] = 279302,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Pillar of Frost",
				["spellID"] = 51271,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Bonestorm",
				["spellID"] = 194844,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Gorefiend's Grasp",
				["spellID"] = 108199,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Dancing Rune Weapon",
				["spellID"] = 49028,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Tombstone",
				["spellID"] = 219809,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Blood Tap",
				["spellID"] = 221699,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Blooddrinker",
				["spellID"] = 206931,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Consumption",
				["spellID"] = 274156,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Rune Tap",
				["spellID"] = 194679,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Unholy Assault",
				["spellID"] = 207289,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Vampiric Blood",
				["spellID"] = 55233,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Summon Gargoyle",
				["spellID"] = 49206,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Apocalypse",
				["spellID"] = 275699,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Dark Transformation",
				["spellID"] = 63560,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Army of the Dead",
				["spellID"] = 42650,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Frostscythe",
				["spellID"] = 207230,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Core"],
				["name"] = "Reaper's Mark",
				["spellID"] = 439843,
			},
			{
				["class"] = "DEATHKNIGHT",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Death Charge",
				["spellID"] = 444347,
			},
		},
		["HUNTER"] = {
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Freezing Trap",
				["spellID"] = 187650,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Flare",
				["spellID"] = 1543,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Feign Death",
				["spellID"] = 5384,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Disengage",
				["spellID"] = 781,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Personal Defensive"],
				["name"] = "Aspect of the Turtle",
				["spellID"] = 186265,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Aspect of the Cheetah",
				["spellID"] = 186257,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Personal Defensive"],
				["name"] = "Exhilaration",
				["spellID"] = 109304,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Personal Defensive"],
				["name"] = "Survival of the Fittest",
				["spellID"] = 264735,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Personal Defensive"],
				["name"] = "Fortitude of the Bear",
				["spellID"] = 392956,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Muzzle",
				["spellID"] = 187707,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Flanking Strike",
				["spellID"] = 269751,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Harpoon",
				["spellID"] = 190925,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Fury of the Eagle",
				["spellID"] = 203415,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Core"],
				["name"] = "Coordinated Assault",
				["spellID"] = 360952,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Core"],
				["name"] = "Spearhead",
				["spellID"] = 360966,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Bursting Shot",
				["spellID"] = 186387,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Rapid Fire",
				["spellID"] = 257044,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Core"],
				["name"] = "Trueshot",
				["spellID"] = 288613,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Tranquilizing Shot",
				["spellID"] = 19801,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Intimidation",
				["spellID"] = 19577,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "High Explosive Trap",
				["spellID"] = 236776,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Core"],
				["name"] = "Explosive Shot",
				["spellID"] = 212431,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Misdirection",
				["spellID"] = 34477,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Tar Trap",
				["spellID"] = 187698,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Camouflage",
				["spellID"] = 199483,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Scatter Shot",
				["spellID"] = 213691,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Binding Shot",
				["spellID"] = 109248,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Core"],
				["name"] = "Bloodshed",
				["spellID"] = 321530,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Core"],
				["name"] = "Bestial Wrath",
				["spellID"] = 19574,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Core"],
				["name"] = "Call of the Wild",
				["spellID"] = 359844,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Black Arrow",
				["spellID"] = 468037,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Other"],
				["name"] = "Implosive Trap",
				["spellID"] = 462031,
			},
			{
				["class"] = "HUNTER",
				["type"] = L["Core"],
				["name"] = "Aspect of the Eagle",
				["spellID"] = 186289,
			},
		},
		["EVOKER"] = {
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Fury of the Aspects",
				["spellID"] = 390386,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Emerald Blossom",
				["spellID"] = 355913,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Nullifying Shroud",
				["spellID"] = 378464,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Deep Breath",
				["spellID"] = 357210,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Terror of the Skies",
				["spellID"] = 371032,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Breath of Eons",
				["spellID"] = 403631,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Fire Breath",
				["spellID"] = 357208,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Hover",
				["spellID"] = 358267,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Sleep Walk",
				["spellID"] = 360806,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Emerald Communion",
				["spellID"] = 370960,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Dream Flight",
				["spellID"] = 359816,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Stasis",
				["spellID"] = 370537,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Group Utility"],
				["name"] = "Rewind",
				["spellID"] = 363534,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["External Defensive"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Time Dilation",
				["spellID"] = 357170,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Spiritbloom",
				["spellID"] = 367226,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Dream Breath",
				["spellID"] = 355936,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Shattering Star",
				["spellID"] = 370452,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Eternity Surge",
				["spellID"] = 359073,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Firestorm",
				["spellID"] = 368847,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Dragonrage",
				["spellID"] = 375087,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Group Utility"],
				["name"] = "Time Spiral",
				["spellID"] = 374968,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Personal Defensive"],
				["name"] = "Renewing Blaze",
				["spellID"] = 374348,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Group Utility"],
				["name"] = "Zephyr",
				["spellID"] = 374227,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Rescue",
				["spellID"] = 370665,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Quell",
				["spellID"] = 351338,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Oppressing Roar",
				["spellID"] = 372048,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Cauterizing Flame",
				["spellID"] = 374251,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Personal Defensive"],
				["name"] = "Obsidian Scales",
				["spellID"] = 363916,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Landslide",
				["spellID"] = 358385,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Tip the Scales",
				["spellID"] = 370553,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Personal Defensive"],
				["name"] = "Verdant Embrace",
				["spellID"] = 360995,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Expunge",
				["spellID"] = 365585,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Naturalize",
				["spellID"] = 360823,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Spatial Paradox",
				["spellID"] = 406732,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Time Skip",
				["spellID"] = 404977,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["External Defensive"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Blistering Scales",
				["spellID"] = 360827,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Upheaval",
				["spellID"] = 396286,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Ebon Might",
				["spellID"] = 395152,
			},
			{
				["class"] = "EVOKER",
				["type"] = L["Other"],
				["name"] = "Engulf",
				["spellID"] = 443328,
			},
		},
		["DRUID"] = {
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Dash",
				["spellID"] = 1850,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Personal Defensive"],
				["name"] = "Thorns",
				["spellID"] = 305497,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Nature's Cure",
				["spellID"] = 88423,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Prowl",
				["spellID"] = 5215,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Personal Defensive"],
				["name"] = "Barkskin",
				["spellID"] = 22812,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Growl",
				["spellID"] = 6795,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Nature's Swiftness",
				["spellID"] = 132158,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Cenarion Ward",
				["spellID"] = 102351,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Tranquility",
				["spellID"] = 740,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Overgrowth",
				["spellID"] = 203651,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Incarnation: Tree of Life",
				["spellID"] = 33891,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["name"] = "Convoke the Spirits",
				["spellID"] = 391528,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Adaptive Swarm",
				["spellID"] = 391888,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Invigorate",
				["spellID"] = 392160,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Flourish",
				["spellID"] = 197721,
			},
			{
				["class"] = "DRUID",
				["type"] = L["External Defensive"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Ironbark",
				["spellID"] = 102342,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Berserk",
				["spellID"] = 106951,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Feral Frenzy",
				["spellID"] = 274837,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Incarnation: Avatar of Ashamane",
				["spellID"] = 102543,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Personal Defensive"],
				["name"] = "Survival Instincts",
				["spellID"] = 61336,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Tiger's Fury",
				["spellID"] = 5217,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Incarnation: Guardian of Ursoc",
				["spellID"] = 102558,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Rage of the Sleeper",
				["spellID"] = 200851,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Personal Defensive"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Pulverize",
				["spellID"] = 80313,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Bristling Fur",
				["spellID"] = 155835,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Wild Charge",
				["spellID"] = 102401,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Tiger Dash",
				["spellID"] = 252216,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Remove Corruption",
				["spellID"] = 2782,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Typhoon",
				["spellID"] = 132469,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["name"] = "Frenzied Regeneration",
				["spellID"] = 22842,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Maim",
				["spellID"] = 22570,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Skull Bash",
				["spellID"] = 106839,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Soothe",
				["spellID"] = 2908,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["name"] = "Heart of the Wild",
				["spellID"] = 319454,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Renewal",
				["spellID"] = 108238,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Group Utility"],
				["name"] = "Stampeding Roar",
				["spellID"] = 77764,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Mighty Bash",
				["spellID"] = 5211,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Incapacitating Roar",
				["spellID"] = 99,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Mass Entanglement",
				["spellID"] = 102359,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Ursol's Vortex",
				["spellID"] = 102793,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Innervate",
				["spellID"] = 29166,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Nature's Vigil",
				["spellID"] = 124974,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["name"] = "Force of Nature",
				["spellID"] = 205636,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Celestial Alignment",
				["spellID"] = 194223,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Wild Mushroom",
				["spellID"] = 88747,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Fury of Elune",
				["spellID"] = 202770,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "New Moon",
				["spellID"] = 274281,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Solar Beam",
				["spellID"] = 78675,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:damager"] = true },
				["name"] = "Warrior of Elune",
				["spellID"] = 202425,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Other"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Lunar Beam",
				["spellID"] = 204066,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:tank"] = true },
				["name"] = "Berserk",
				["spellID"] = 50334,
			},
			{
				["class"] = "DRUID",
				["type"] = L["Core"],
				["role"] = { ["role:healer"] = true },
				["name"] = "Grove Guardians",
				["spellID"] = 102693,
			},
		},
		["WARLOCK"] = {
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Oblivion",
				["spellID"] = 417537,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Call Observer",
				["spellID"] = 201996,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = 461917,
				["name"] = "Bane of Havoc",
				["spellID"] = 200546,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = 266,
				["name"] = "Felstorm",
				["spellID"] = 89751,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["name"] = "Command Demon",
				["spellID"] = 119898,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["name"] = "Demonic Circle: Teleport",
				["spellID"] = 48020,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Personal Defensive"],
				["name"] = "Unending Resolve",
				["spellID"] = 104773,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Fel Domination",
				["spellID"] = 333889,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Amplify Curse",
				["spellID"] = 328774,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Dark Pact",
				["spellID"] = 108416,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Shadowfury",
				["spellID"] = 30283,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Howl of Terror",
				["spellID"] = 5484,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Mortal Coil",
				["spellID"] = 6789,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Dimensional Rift",
				["spellID"] = 387976,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Cataclysm",
				["spellID"] = 152108,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Soul Fire",
				["spellID"] = 6353,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Havoc",
				["spellID"] = 80240,
				["talent"] = 461917,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Summon Infernal",
				["spellID"] = 1122,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Power Siphon",
				["spellID"] = 264130,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Grimoire: Felguard",
				["spellID"] = 111898,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Summon Vilefiend",
				["spellID"] = 264119,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Demonic Strength",
				["spellID"] = 267171,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Bilescourge Bombers",
				["spellID"] = 267211,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Call Dreadstalkers",
				["spellID"] = 104316,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Summon Demonic Tyrant",
				["spellID"] = 265187,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Summon Darkglare",
				["spellID"] = 205180,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Vile Taint",
				["spellID"] = 278350,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Phantom Singularity",
				["spellID"] = 205179,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Grimoire of Sacrifice",
				["spellID"] = 108503,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = { 386997, 321077 },
				["name"] = "Soul Rot",
				["spellID"] = 386997,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Channel Demonfire",
				["spellID"] = 196447,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Malevolence",
				["spellID"] = 442726,
			},
			{
				["class"] = "WARLOCK",
				["type"] = L["Other"],
				["spec"] = 386689,
				["name"] = "Demonic Healthstone",
				["spellID"] = 452930,
			},
		},
		["PRIEST"] = {
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Dark Archangel",
				["spellID"] = 197871,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = { 375901, 321079 },
				["name"] = "Mindgames",
				["spellID"] = 375901,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = { 256, 257 },
				["name"] = "Purify",
				["spellID"] = 527,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["name"] = "Psychic Scream",
				["spellID"] = 8122,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["name"] = "Fade",
				["spellID"] = 586,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["name"] = "Desperate Prayer",
				["spellID"] = 19236,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Divine Word",
				["spellID"] = 372760,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = { 205385, 457042 },
				["name"] = "Shadow Crash",
				["spellID"] = 205385,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Group Utility"],
				["spec"] = true,
				["name"] = "Power Word: Barrier",
				["spellID"] = 62618,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Evangelism",
				["spellID"] = 472433,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Mindbender",
				["spellID"] = 123040,
				["talent"] = 451234,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["External Defensive"],
				["spec"] = true,
				["name"] = "Pain Suppression",
				["spellID"] = 33206,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Rapture",
				["spellID"] = 47536,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Lightwell",
				["spellID"] = 372835,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Restitution",
				["spellID"] = 391124,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Empyreal Blaze",
				["spellID"] = 372616,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Apotheosis",
				["spellID"] = 200183,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Group Utility"],
				["spec"] = true,
				["name"] = "Symbol of Hope",
				["spellID"] = 64901,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Group Utility"],
				["spec"] = true,
				["name"] = "Divine Hymn",
				["spellID"] = 64843,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Holy Word: Sanctify",
				["spellID"] = 34861,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["External Defensive"],
				["spec"] = true,
				["name"] = "Guardian Spirit",
				["spellID"] = 47788,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Holy Word: Serenity",
				["spellID"] = 2050,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Power Word: Radiance",
				["spellID"] = 194509,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Holy Word: Chastise",
				["spellID"] = 88625,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Mindbender",
				["spellID"] = 200174,
				["talent"] = 451234,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Silence",
				["spellID"] = 15487,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Psychic Horror",
				["spellID"] = 64044,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Void Torrent",
				["spellID"] = 263165,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Dark Ascension",
				["spellID"] = 391109,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Void Eruption",
				["spellID"] = 228260,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Dispersion",
				["spellID"] = 47585,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["External Defensive"],
				["spec"] = true,
				["name"] = "Void Shift",
				["spellID"] = 108968,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Power Word: Life",
				["spellID"] = 373481,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Halo",
				["spellID"] = 120644,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Halo",
				["spellID"] = 120517,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Group Utility"],
				["spec"] = true,
				["name"] = "Vampiric Embrace",
				["spellID"] = 15286,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Power Infusion",
				["spellID"] = 10060,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Group Utility"],
				["spec"] = true,
				["name"] = "Mass Dispel",
				["spellID"] = 32375,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Angelic Feather",
				["spellID"] = 121536,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Purify Disease",
				["spellID"] = 213634,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Void Tendrils",
				["spellID"] = 108920,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Dominate Mind",
				["spellID"] = 205364,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Shadow Word: Death",
				["spellID"] = 32379,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Shadowfiend",
				["spellID"] = 34433,
				["talent"] = { 200174, 123040, 451234 },
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Leap of Faith",
				["spellID"] = 73325,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Luminous Barrier",
				["spellID"] = 271466,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Ultimate Penitence",
				["spellID"] = 421453,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = { 256, 258 },
				["name"] = "Mind Blast",
				["duration"] = { [256] = 24, [258] = 9 },
				["spellID"] = 8092,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Other"],
				["spec"] = 428924,
				["name"] = "Premonition",
				["spellID"] = 428933,
			},
			{
				["class"] = "PRIEST",
				["type"] = L["Core"],
				["spec"] = 451234,
				["name"] = "Voidwraith",
				["spellID"] = 451234,
			},
		},
		["PALADIN"] = {
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = 65,
				["name"] = "Cleanse",
				["spellID"] = 4987,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["External Defensive"],
				["spec"] = 199452,
				["name"] = "Ultimate Sacrifice",
				["spellID"] = 199448,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["name"] = "Hammer of Justice",
				["spellID"] = 853,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["name"] = "Hand of Reckoning",
				["spellID"] = 62124,
				["talent"] = 207028,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["name"] = "Divine Shield",
				["spellID"] = 642,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = { 70 },
				["name"] = "Divine Protection",
				["spellID"] = 403876,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = { 65 },
				["name"] = "Divine Protection",
				["spellID"] = 498,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Ardent Defender",
				["spellID"] = 31850,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Sentinel",
				["spellID"] = 389539,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Gift of the Golden Val'kyr",
				["spellID"] = 378279,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Bastion of Light",
				["spellID"] = 378974,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Guardian of Ancient Kings",
				["spellID"] = 86659,
				["talent"] = 228049,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = { 375576, 321076 },
				["name"] = "Divine Toll",
				["spellID"] = 375576,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Eye of Tyr",
				["spellID"] = 387174,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Avenger's Shield",
				["spellID"] = 31935,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Moment of Glory",
				["spellID"] = 327193,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Cleanse Toxins",
				["spellID"] = 213644,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Eye for an Eye",
				["spellID"] = 205191,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Wake of Ashes",
				["spellID"] = 255937,
				["talent"] = 384052,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Crusade",
				["spellID"] = 231895,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Execution Sentence",
				["spellID"] = 343527,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Shield of Vengeance",
				["spellID"] = 184662,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Final Reckoning",
				["spellID"] = 343721,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["External Defensive"],
				["spec"] = true,
				["name"] = "Barrier of Faith",
				["spellID"] = 148039,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Aura Mastery",
				["spellID"] = 31821,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Holy Prism",
				["spellID"] = 114165,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Avenging Crusader",
				["spellID"] = 216331,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Tyr's Deliverance",
				["spellID"] = 200652,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = { 388007, 321077 },
				["name"] = "Blessing of Summer",
				["spellID"] = 388007,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Lay on Hands",
				["spellID"] = 633,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Blinding Light",
				["spellID"] = 115750,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Repentance",
				["spellID"] = 20066,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Blessing of Freedom",
				["spellID"] = 1044,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Rebuke",
				["spellID"] = 96231,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Avenging Wrath",
				["duration"] = { [70] = 60, ["default"] = 120 },
				["spellID"] = 31884,
				["talent"] = { 216331, 231895, 389539, 458359 },
				disabledSpec = {
					[65] = { arena = true, pvp = true, party = true, raid = true, scenario = true, none = true },
				},
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = 31884,
				["name"] = "Avenging Wrath",
				["spellID"] = 384376,
				["talent"] = { 216331, 231895, 389539 },
				disabledSpec = {
					[66] = { arena = true, pvp = true, party = true, raid = true, scenario = true, none = true },
					[70] = { arena = true, pvp = true, party = true, raid = true, scenario = true, none = true },
				},
			},
			{
				["class"] = "PALADIN",
				["type"] = L["External Defensive"],
				["spec"] = true,
				["name"] = "Blessing of Sacrifice",
				["spellID"] = 6940,
				["talent"] = 199452,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["External Defensive"],
				["spec"] = true,
				["name"] = "Blessing of Protection",
				["spellID"] = 1022,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Turn Evil",
				["spellID"] = 10326,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Divine Steed",
				["spellID"] = 190784,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Daybreak",
				["spellID"] = 414170,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Hand of Divinity",
				["spellID"] = 414273,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Divine Hammer",
				["spellID"] = 198034,
			},
			{
				["class"] = "PALADIN",
				["type"] = L["External Defensive"],
				["spec"] = 432459,
				["name"] = "Holy Bulwark",
				["spellID"] = 432472,
			},
		},
		["SHAMAN"] = {
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["name"] = "Earthbind Totem",
				["spellID"] = 2484,
				["talent"] = 51485,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["name"] = "Bloodlust",
				["spellID"] = 2825,
				["pve"] = true,
				["talent"] = 193876,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = 264,
				["name"] = "Purify Spirit",
				["spellID"] = 77130,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["name"] = "Reincarnation",
				["spellID"] = 20608,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Feral Lunge",
				["spellID"] = 196884,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Doom Winds",
				["spellID"] = 384352,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = { 375982, 321078 },
				["name"] = "Primordial Wave",
				["spellID"] = 375982,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Primordial Wave",
				["spellID"] = 428332,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Feral Spirit",
				["spellID"] = 51533,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Fire Elemental",
				["spellID"] = 198067,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Storm Elemental",
				["spellID"] = 192249,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Stormkeeper",
				["spellID"] = 191634,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Stormkeeper",
				["spellID"] = 383009,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Ascendance",
				["spellID"] = 114049,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Liquid Magma Totem",
				["spellID"] = 192222,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Healing Tide Totem",
				["spellID"] = 108280,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Spirit Link Totem",
				["spellID"] = 98008,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Mana Tide Totem",
				["spellID"] = 16191,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Earthen Wall Totem",
				["spellID"] = 198838,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Group Utility"],
				["spec"] = true,
				["name"] = "Ancestral Protection Totem",
				["spellID"] = 207399,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Cloudburst Totem",
				["spellID"] = 157153,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Wellspring",
				["spellID"] = 197995,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Astral Shift",
				["spellID"] = 108271,
			}, --["talent"]=210918, },
			{
				["class"] = "SHAMAN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Earth Elemental",
				["spellID"] = 198103,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Spiritwalker's Grace",
				["spellID"] = 79206,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Wind Shear",
				["spellID"] = 57994,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Group Utility"],
				["spec"] = true,
				["name"] = "Tremor Totem",
				["spellID"] = 8143,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Capacitor Totem",
				["spellID"] = 192058,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Cleanse Spirit",
				["spellID"] = 51886,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Greater Purge",
				["spellID"] = 378773,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Hex",
				["spellID"] = 51514,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Nature's Guardian",
				["spellID"] = 30884,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Earthgrab Totem",
				["spellID"] = 51485,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Group Utility"],
				["spec"] = true,
				["name"] = "Wind Rush Totem",
				["spellID"] = 192077,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Gust of Wind",
				["spellID"] = 192063,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Spirit Walk",
				["spellID"] = 58875,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Totemic Recall",
				["spellID"] = 108285,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Poison Cleansing Totem",
				["spellID"] = 383013,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Tranquil Air Totem",
				["spellID"] = 383019,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Lightning Lasso",
				["spellID"] = 305483,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Thunderstorm",
				["spellID"] = 51490,
				["talent"] = { 204403, 378779 },
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = 204403,
				["name"] = "Traveling Storm",
				["spellID"] = 204406,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Thundershock",
				["spellID"] = 378779,
				["talent"] = 204403,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Healing Stream Totem",
				["spellID"] = 5394,
				["talent"] = 157153,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Sundering",
				["spellID"] = 197214,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Nature's Swiftness",
				["spellID"] = 378081,
				["talent"] = 443454,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Other"],
				["spec"] = true,
				["name"] = "Ancestral Swiftness",
				["spellID"] = 443454,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Personal Defensive"],
				["spec"] = true,
				["name"] = "Stone Bulwark Totem",
				["spellID"] = 108270,
			},
			{
				["class"] = "SHAMAN",
				["type"] = L["Core"],
				["spec"] = true,
				["name"] = "Surging Totem",
				["spellID"] = 444995,
			},
		},
		["MAGE"] = {
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Time Warp",
				["spellID"] = 80353,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Counterspell",
				["spellID"] = 2139,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Frost Nova",
				["spellID"] = 122,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Blink",
				["spellID"] = 1953,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Invisibility",
				["spellID"] = 66,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Shifting Power",
				["spellID"] = 382440,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Ring of Frost",
				["spellID"] = 113724,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Meteor",
				["spellID"] = 153561,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Dragon's Breath",
				["spellID"] = 31661,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Displacement",
				["spellID"] = 389713,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Greater Invisibility",
				["spellID"] = 110959,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Blast Wave",
				["spellID"] = 157981,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Shimmer",
				["spellID"] = 212653,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Ice Floes",
				["spellID"] = 108839,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Mass Polymorph",
				["spellID"] = 383121,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Alter Time",
				["spellID"] = 342245,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Remove Curse",
				["spellID"] = 475,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Ice Barrier",
				["spellID"] = 11426,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Blazing Barrier",
				["spellID"] = 235313,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Prismatic Barrier",
				["spellID"] = 235450,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Ice Block",
				["spellID"] = 45438,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Mirror Image",
				["spellID"] = 55342,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Ice Nova",
				["spellID"] = 157997,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Presence of Mind",
				["spellID"] = 205025,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Evocation",
				["spellID"] = 12051,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Ray of Frost",
				["spellID"] = 205021,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Icy Veins",
				["spellID"] = 12472,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Summon Water Elemental",
				["spellID"] = 31687,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Frozen Orb",
				["spellID"] = 84714,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Flurry",
				["spellID"] = 44614,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Comet Storm",
				["spellID"] = 153595,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Combustion",
				["spellID"] = 190319,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Supernova",
				["spellID"] = 157980,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Arcane Surge",
				["spellID"] = 365350,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Touch of the Magi",
				["spellID"] = 321507,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Core"],
				["name"] = "Arcane Orb",
				["spellID"] = 153626,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Group Utility"],
				["name"] = "Mass Barrier",
				["spellID"] = 414660,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Group Utility"],
				["name"] = "Mass Invisibility",
				["spellID"] = 414664,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Cauterize",
				["spellID"] = 86949,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Cold Snap",
				["spellID"] = 235219,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Personal Defensive"],
				["name"] = "Ice Cold",
				["spellID"] = 414658,
			},
			{
				["class"] = "MAGE",
				["type"] = L["Other"],
				["name"] = "Cone of Cold",
				["spellID"] = 120,
			},
		},
	},
	other = {
		["RACIAL"] = {
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Will to Survive",
				["race"] = 1,
				["spellID"] = 59752,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Blood Fury",
				["race"] = 2,
				["spellID"] = 20572,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Stoneform",
				["race"] = 3,
				["spellID"] = 20594,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Shadowmeld",
				["race"] = 4,
				["spellID"] = 58984,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Will of the Forsaken",
				["race"] = 5,
				["spellID"] = 7744,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "War Stomp",
				["race"] = 6,
				["spellID"] = 20549,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Escape Artist",
				["race"] = 7,
				["spellID"] = 20589,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Berserking",
				["race"] = 8,
				["spellID"] = 26297,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Rocket Jump",
				["race"] = 9,
				["spellID"] = 69070,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Arcane Torrent",
				["race"] = 10,
				["spellID"] = 129597,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Gift of the Naaru",
				["race"] = 11,
				["spellID"] = 59542,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Darkflight",
				["race"] = 22,
				["spellID"] = 68992,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Quaking Palm",
				["race"] = { 25, 26 },
				["spellID"] = 107079,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Arcane Pulse",
				["race"] = 27,
				["spellID"] = 260364,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Bull Rush",
				["race"] = 28,
				["spellID"] = 255654,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Spatial Rift",
				["race"] = 29,
				["spellID"] = 256948,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Light's Judgment",
				["race"] = 30,
				["spellID"] = 255647,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Regeneratin'",
				["race"] = 31,
				["spellID"] = 291944,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Haymaker",
				["race"] = 32,
				["spellID"] = 287712,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Fireblood",
				["race"] = 34,
				["spellID"] = 265221,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Bag of Tricks",
				["race"] = 35,
				["spellID"] = 312411,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Ancestral Call",
				["race"] = 36,
				["spellID"] = 274738,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Hyper Organic Light Originator",
				["race"] = 37,
				["spellID"] = 312924,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Emergency Failsafe",
				["race"] = 37,
				["spellID"] = 312916,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Tail Swipe",
				["race"] = { 52, 70 },
				["spellID"] = 368970,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Wing Buffet",
				["race"] = { 52, 70 },
				["spellID"] = 357214,
			},
			{
				["class"] = "RACIAL",
				["type"] = L["Racial"],
				["name"] = "Azerite Surge",
				["race"] = { 84, 85 },
				["spellID"] = 436344,
			},
		},
		["CONSUMABLE"] = {
			{
				["class"] = "CONSUMABLE",
				["type"] = L["Consumable"],
				["name"] = "Algari Healing Potion",
				["spellID"] = 431416,
				["item"] = nil,
			},
			{
				["class"] = "CONSUMABLE",
				["type"] = L["Consumable"],
				["name"] = "Invigorating Healing Potion",
				["spellID"] = 1238009,
				["item"] = nil,
			},
			{
				["class"] = "CONSUMABLE",
				["type"] = L["Consumable"],
				["name"] = "Activate Weyrnstone",
				["spellID"] = 408234,
				["item"] = 205146,
			},
			{
				["class"] = "CONSUMABLE",
				["type"] = L["Consumable"],
				["name"] = "Healthstone",
				["spellID"] = 6262,
				["item"] = 5512,
			},
			{
				["class"] = "CONSUMABLE",
				["type"] = L["Consumable"],
				["name"] = "Demonic Gateway",
				["spellID"] = 113942,
				["item"] = 0,
			},
		},
	},
}

---@return table<integer, integer>
function Private.spellDB.GetSpellRemappings()
	return {
		[430703] = 468037, -- Black Arrow
		[246287] = 472433, -- Evangelism
	}
end
