name: Package

on:
    workflow_dispatch:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
            - "!**-alpha**"
            - "!**-beta**"
        paths-ignore:
            - ".github/**"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Checkout latest tag
              run: |
                git fetch --tags
                latest_tag=$(git tag --sort=-creatordate | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
                echo "Checking out tag: $latest_tag"
                git checkout $latest_tag

            - name: Package
              uses: BigWigsMods/packager@master
              env:
                  CF_API_KEY: ${{ secrets.CF_API_KEY }}
                  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
