name: Send TEST Release Notifications

# 'workflow_dispatch' means it will only be manually triggerd via actions menu.
on:
  workflow_dispatch:

jobs:
  test-release-notification-output:
    runs-on: ubuntu-latest

    outputs:
      changeLogText: ${{ steps.readChangelog.outputs.text }}

    steps:
      # we first have to clone the AddOn project, this is a required step
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # gets git history for changelogs

      - name: Hack around https://github.com/actions/checkout/issues/290
        run: |
          git fetch --tags --force

      - name: save changelog in variable
        uses: Stanzilla/cat@2.0.2
        id: readChangelog
        with:
          path: CHANGELOG.md

  test-discord-release-notification:
    runs-on: ubuntu-latest
    needs: test-release-notification-output

    env:
      MESSAGE: "TEST NOTIFICATION"

    steps:
      - name: Discord Release Webhook Action
        uses: tsickert/discord-webhook@v7.0.0
        if: success()
        with:
          webhook-url: ${{ secrets.RELEASE_WEBHOOK_URL }}
          embed-title: ${{ env.MESSAGE }}
          embed-url: https://github.com/markoleptic/EncounterPlanner/releases/latest
          embed-description:  ${{needs.test-release-notification-output.outputs.changeLogText}}
