name: Send Release Notifications

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-notification-output:
    runs-on: ubuntu-latest

    outputs:
      changeLogText: ${{ steps.readChangelog.outputs.text }}

    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # gets git history for changelogs

      - name: Hack around https://github.com/actions/checkout/issues/290
        run: |
          git fetch --tags --force

      - name: Save Changelog in Variable
        uses: Stanzilla/cat@2.0.2
        id: readChangelog
        with:
          path: CHANGELOG.md

  discord-release-notification:
    runs-on: ubuntu-latest
    needs: release-notification-output

    env:
      MESSAGE: "New Encounter Planner Release"

    steps:
      - name: Send Discord Notification
        id: discord
        uses: tsickert/discord-webhook@v7.0.0
        if: success()
        with:
          webhook-url: ${{ secrets.RELEASE_WEBHOOK_URL }}
          embed-title: ${{ env.MESSAGE }}
          embed-url: https://github.com/markoleptic/EncounterPlanner/releases/latest
          embed-description:  ${{needs.release-notification-output.outputs.changeLogText}}
